### ISSUE TITLE
change_wallpaper_automation_example.ipynb fails

### ISSUE THREAD

**Issue by oamphan** [OakwoodAI/Automagica#105]
Trying out the example change_wallpaper_automation_example fails with the below error:

```Traceback (most recent call last):
  File "c:\python376\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python376\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python376\Scripts\automagica.exe\__main__.py", line 7, in <module>
  File "c:\python376\lib\site-packages\automagica\cli.py", line 624, in main
    app = Automagica()
  File "c:\python376\lib\site-packages\automagica\cli.py", line 139, in __init__
    exec(script, globals())
  File "<string>", line 3, in <module>
  File "c:\python376\lib\site-packages\automagica\utilities.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "c:\python376\lib\site-packages\automagica\activities.py", line 6569, in download_file_from_url
    if not filename:
UnboundLocalError: local variable 'filename' referenced before assignment


from automagica import *
# Download the file 
downloaded_image = download_file_from_url('https://automagica.com/examples/wallpaper.jpg')
# Set image as wallpaper
set_wallpaper(downloaded_image)
```
I'm getting this error both in Windows 10 and Fedora 31. Is it something in my install or something with automagica?

**Comment by koenvaneijk** [comment]
@oamphan please update to the latest version of Automagica, this should be fixed!
