### ISSUE TITLE
I can not pip install automagica

### ISSUE THREAD

**Issue by 2bo** [OakwoodAI/Automagica#38]
I executed "pip install https://github.com/OakwoodAI/automagica/tarball/master" under venv.
But, It occurred error. 

[My environment]
OS: Mac OS Sierra 10.12.6
Python:3.7.1, pip 18.1
```
(venv) MBA:automagica_example koh$ pip install https://github.com/OakwoodAI/automagica/tarball/master
Collecting https://github.com/OakwoodAI/automagica/tarball/master
  Downloading https://github.com/OakwoodAI/automagica/tarball/master
     | 47.4MB 503kB/s
Collecting socketIO-client==0.7.2 (from Automagica==0.3.1)
  Using cached https://files.pythonhosted.org/packages/12/d4/abeb2596c2f16276c66910362b27d04b8d2cf12a746dcccf1d00de3f691b/socketIO-client-0.7.2.tar.gz
Collecting PyAutoGUI==0.9.36 (from Automagica==0.3.1)
  Using cached https://files.pythonhosted.org/packages/2e/83/89b5adbc37d1bbf7b486a2c1c00e8037e6f801e8c053c4897bb82d9510c6/PyAutoGUI-0.9.36.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/20/rcd4mbg52tl3l94t2lmktylr0000gn/T/pip-install-4hrz700t/PyAutoGUI/pyautogui/_pyautogui_osx.py", line 5, in <module>
        import Quartz
    ModuleNotFoundError: No module named 'Quartz'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/20/rcd4mbg52tl3l94t2lmktylr0000gn/T/pip-install-4hrz700t/PyAutoGUI/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/private/var/folders/20/rcd4mbg52tl3l94t2lmktylr0000gn/T/pip-install-4hrz700t/PyAutoGUI/pyautogui/__init__.py", line 110, in <module>
        from . import _pyautogui_osx as platformModule
      File "/private/var/folders/20/rcd4mbg52tl3l94t2lmktylr0000gn/T/pip-install-4hrz700t/PyAutoGUI/pyautogui/_pyautogui_osx.py", line 7, in <module>
        assert False, "You must first install pyobjc-core and pyobjc: https://pyautogui.readthedocs.io/en/latest/install.html"
    AssertionError: You must first install pyobjc-core and pyobjc: https://pyautogui.readthedocs.io/en/latest/install.html

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/20/rcd4mbg52tl3l94t2lmktylr0000gn/T/pip-install-4hrz700t/PyAutoGUI/
```

**Comment by tvturnhout** [comment]
Hi 2bo, we do not support Mac OS officially. However thanks for the very useful feedback, we will take a look at it and see if we can add Sierra 10.12.6 support in the next patch.
