### ISSUE TITLE
 from win32api import LoadKeyboardLayout ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by supernooba** [OakwoodAI/Automagica#42]
Hi,

I tried the nla examples (google.nla, wikipedia.nla & youtube.nla) however, i stumble this error:

DevTools listening on ws://127.0.0.1:12531/devtools/browser/51d19e8a-bd38-4e1f-8156-0a470e3df24e
Traceback (most recent call last):
  File "c:\users\mestrera\appdata\local\continuum\miniconda3\envs\automagicaenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mestrera\appdata\local\continuum\miniconda3\envs\automagicaenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mestrera\AppData\Local\Continuum\miniconda3\envs\automagicaEnv\Scripts\nla.exe\__main__.py", line 9, in <module>
  File "c:\users\mestrera\appdata\local\continuum\miniconda3\envs\automagicaenv\lib\site-packages\nla\command_line.py", line 4, in main
    nla.main()
  File "c:\users\mestrera\appdata\local\continuum\miniconda3\envs\automagicaenv\lib\site-packages\nla\__init__.py", line 39, in main
    Type(text=query)
  File "c:\users\mestrera\appdata\local\continuum\miniconda3\envs\automagicaenv\lib\site-packages\automagica\activities.py", line 115, in Type
    from win32api import LoadKeyboardLayout
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by koenvaneijk** [comment]
Hi @supernooba,

Thank you for opening this issue.

This error occurs when you are using Python x64 (with the 64-bit DLLs), this won't work unfortunately.

Please check the following discussion on Stackoverflow:
https://stackoverflow.com/questions/46640587/importerror-dll-load-failed-1-is-not-a-valid-win32-application-while-importin

Closing this issue as this is not an issue with the Automagica library, rather with your specific installation of Python.

Kind regards,
Koen
