### ISSUE TITLE
Browser example got an error

### ISSUE THREAD

**Issue by Panepo** [OakwoodAI/Automagica#59]
Hi there,

I got an error while running [this browser example](https://github.com/OakwoodAI/Automagica/blob/master/examples/browser/app.py). The error message is as follows:
```
DevTools listening on ws://127.0.0.1:12790/devtools/browser/c4f2757f-d494-46ab-890e-7e0eb97da4ae
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    browser.find_element_by_xpath('//*[@id="lst-ib"]').send_keys('oakwoodai automagica')
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    'value': value})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="lst-ib"]"}
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.16299 x86_64)
```
The environment is win10 1709, python 3.7.3 and chrome 75.0.3770.100.
Is there anything I missed while installing?
Thanks

**Comment by bkeskin91** [comment]
Hey @Panepo 

it seems you try to access an HTML Element that isn't there.
Look at the Acception:
 Unable to locate element: {"method":"xpath","selector":"//*[@id="lst-ib"]"}
so you basically try to access the html Element with the id ,,lst-ib" if there is no such element this given exception will be thrown. 
Check the Documentation for further informations.

**Comment by Panepo** [comment]
Hi @bkeskin91 

I fix those two line and it's works
```
# Enter searchterm
browser.find_element_by_name('q').send_keys('oakwoodai automagica')
# Click on search button
browser.find_element_by_name('q').submit()
```
Thanks
