### ISSUE TITLE
Registering local client to portal failed.

### ISSUE THREAD

**Issue by jaekim0908** [OakwoodAI/Automagica#76]
automagica --login "ab36..."

Error message:
Traceback (most recent call last):
  File "/anaconda3/envs/py37/bin/automagica", line 8, in <module>
    sys.exit(main())
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/automagica/cli.py", line 415, in main
    app = Automagica()
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/automagica/cli.py", line 89, in __init__
    self.login(args.login)
  File "/anaconda3/envs/py37/lib/python3.7/site-packages/automagica/cli.py", line 322, in login
    subprocess.Popen(cmd)
  File "/anaconda3/envs/py37/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/envs/py37/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda3/envs/py37/bin/python -m automagica --daemon': '/anaconda3/envs/py37/bin/python -m automagica --daemon'

**Comment by koenvaneijk** [comment]
@jaekim0908 could you provide some more information please?

What kind of OS are you using? It looks like you're using a Linux-based distro?

It seems that the python executable cannot be found at that location. Can you run the command manually? 
```
/anaconda3/envs/py37/bin/python -m automagica --daemon
```

**Comment by LeeRainbow** [comment]
I having this issue in my MAC OS as well. Anyone solve this?

**Comment by koenvaneijk** [comment]
Issues related to the old version of our Portal found at .io-domain (which will be decommissioned soon) are being closed. Please try out our new Portal found at https://portal.automagica.com. It also comes with a new installer which will take care of all the connection nitty gritty for you! :-)
